const data = {
  products: [
    {
      name: 'Nike Slim shirt 1',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/image/p1.jpg',
      countInStock: 10,
      brand: 'Nike',
      ranting: 4.5,
      numReviews: 10,
      descreption: 'high quality shirt',
      price: 100,
    },
    {
      name: 'Nike Slim shirt 2',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/image/p2.jpg',
      countInStock: 10,
      brand: 'Nike',
      ranting: 4.5,
      numReviews: 10,
      descreption: 'high quality shirt',
      price: 200,
    },
    {
      name: 'Nike Slim shirt 3',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/image/p3.jpg',
      countInStock: 10,
      brand: 'Nike',
      ranting: 4.5,
      numReviews: 10,
      descreption: 'high quality shirt',
      price: 300,
    },
    {
      name: 'Nike Slim shirt 4',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/image/p4.jpg',
      countInStock: 10,
      brand: 'Nike',
      ranting: 4.5,
      numReviews: 10,
      descreption: 'high quality shirt',
      price: 400,
    },
  ],
};
export default data;
