const data = {
  products: [
    {
      name: 'Nike Slim shirt 1',
      slug: 'nike-slim-shirt-1',
      category: 'Shirts',
      image: '/image/p1.jpg',
      countInStock: 5,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 10,
      description: 'high quality shirt',
      price: 100,
    },
    {
      name: 'Nike Slim shirt 2',
      slug: 'nike-slim-shirt-2',
      category: 'Shirts',
      image: '/image/p2.jpg',
      countInStock: 0,
      brand: 'Nike',
      rating: 5,
      numReviews: 10,
      description: 'high quality shirt',
      price: 200,
    },
    {
      name: 'Nike Slim shirt 3',
      slug: 'nike-slim-shirt-3',
      category: 'Shirts',
      image: '/image/p3.jpg',
      countInStock: 0,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality shirt',
      price: 300,
    },
    {
      name: 'Nike Slim shirt 4',
      slug: 'nike-slim-shirt-4',
      category: 'Shirts',
      image: '/image/p4.jpg',
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
      price: 400,
    },
  ],
};
export default data;
